name: Haftalık Plan Oluşturucu
on:
  workflow_dispatch:
  schedule:
    - cron: '30 18 * * 0'

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  automation:
    runs-on: ubuntu-latest
    steps:
      - name: Repo'yu Kontrol Et
        uses: actions/checkout@v4

      - name: Test Çıktısı
        run: echo "Otomasyon altyapısı hazır ve Node.js 24 uyumlu!"
